AEGIS-O Documentation
=====================

**Universal AI Safety Protocol**

.. toctree::
   :maxdepth: 2

Quick Start::

    from aegis_omega import create_aegis_for_eu_ai_act
    aegis = create_aegis_for_eu_ai_act()

Indices
=======

* :ref:genindex
"@ | Set-Content "docs/index.rst"

# 4. Create docs/Makefile
@"
SPHINXBUILD = sphinx-build
SOURCEDIR = .
BUILDDIR = _build

html:
    $(SPHINXBUILD) -b html $(SOURCEDIR) $(BUILDDIR)/html
